[env:mhetesp32devkit]
platform = espressif32
board = mhetesp32devkit
framework = espidf
board_build.partitions = partitions.csv
board_upload.flash_size = 4MB
monitor_speed = 115200
board_build.embed_txtfiles = 
    src/azure_ca.pem
build_flags = 
    -D SDKCONFIG_H
    -D PROJECT_VER=\"1.0.0\"
    -I "$PROJECT_PACKAGES_DIR/framework-espidf/components/freertos/FreeRTOS-Kernel/include"
    -I "$PROJECT_PACKAGES_DIR/framework-espidf/components/freertos/FreeRTOS-Kernel/include/freertos" 
    -I components/azureazure_sdk