[env:mhetesp32devkit]
platform = espressif32
board = mhetesp32devkit
framework = espidf
monitor_speed = 115200

build_flags = 
    -D SDKCONFIG_H
    -D PROJECT_VER=\"1.0.0\"
    -I "$PROJECT_PACKAGES_DIR/framework-espidf/components/freertos/FreeRTOS-Kernel/include"
    -I "$PROJECT_PACKAGES_DIR/framework-espidf/components/freertos/FreeRTOS-Kernel/include/freertos" 
    -I components/azureazure_sdk